# Automatically close pull requests created from a forked repository
# if the target branch is either "dev" or "main".
name: Validate PR

on:
  pull_request_target:

jobs:
  validate-pr:
    runs-on: ubuntu-22.04

    steps:
      - name: Check target branch
        run: |
          echo "PoC works"
          sleep 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
